# Generated by Django 5.2.1 on 2025-05-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_enrolment_price_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='instructor_id',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='enrolment',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='user_id',
            new_name='user',
        ),
    ]
